area-parsers:
  - changed-files:
      - any-glob-to-any-file: 'src/**/parsers/**'

area-factory:
  - changed-files:
      - any-glob-to-any-file: 'src/**/DefaultModuleParserFactory.java'
      - any-glob-to-any-file: 'src/**/api/ModuleParserFactory.java'

area-detection:
  - changed-files:
      - any-glob-to-any-file: 'src/**/DefaultModuleTypeDetector.java'
      - any-glob-to-any-file: 'src/**/util/detector/**'
      - any-glob-to-any-file: 'src/**/util/ScormVersionDetector.java'
      - any-glob-to-any-file: 'src/**/api/ModuleTypeDetector*.java'

area-input:
  - changed-files:
      - any-glob-to-any-file: 'src/**/input/**'

area-output:
  - changed-files:
      - any-glob-to-any-file: 'src/**/output/**'

backend-zip:
  - changed-files:
      - any-glob-to-any-file: 'src/**/ZipFileAccess.java'

backend-local:
  - changed-files:
      - any-glob-to-any-file: 'src/**/LocalFileAccess.java'

backend-s3:
  - changed-files:
      - any-glob-to-any-file: 'src/**/S3FileAccess*.java'
      - any-glob-to-any-file: 'src/**/AbstractS3FileAccess.java'

type-tests:
  - changed-files:
      - any-glob-to-any-file: 'src/test/**'

docs:
  - changed-files:
      - any-glob-to-any-file: 'README.md'
      - any-glob-to-any-file: 'AGENTS.md'
      - any-glob-to-any-file: 'CONTRIBUTING.md'
      - any-glob-to-any-file: 'CODE_OF_CONDUCT.md'
      - any-glob-to-any-file: 'docs/**'

build-ci:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
      - any-glob-to-any-file: 'pom.xml'
