blank_issues_enabled: false
contact_links:
  - name: Q&A and usage discussions
    url: https://github.com/jcputney/elearning-module-parser/discussions
    about: Ask questions, discuss usage, and share ideas.

